### ISSUE TITLE
Cookies breaking request deserialization

### ISSUE THREAD

**Issue by paulsmithkc** [cargo-lambda/cargo-lambda#711] opened 2024-11-01 16:54 UTC
When trying to test out the sam hello world project, I am getting the following error when I try to hit the HTTP endpoint from the browser, postman, or curl.

```
{"type":"https://httpstatuses.com/500","status":500,"title":"Internal Server Error","detail":"missing field `cookies` at line 1 column 40"}
```

I am using the following commands to test the app:

```
sam init
cd sam-app/rust_app
cargo lambda watch
curl http://localhost:9000/hello
```

**main.rs**
```
use lambda_runtime::{run, service_fn, Error, LambdaEvent};
use serde::{Deserialize, Serialize};

#[derive(Deserialize)]
struct Request {
}

#[derive(Serialize)]
struct Response {
    statusCode: i32,
    body: String,
}

async fn function_handler(event: LambdaEvent<Request>) -> Result<Response, Error> {
    let resp = Response {
        statusCode: 200,
        body: "Hello World!".to_string(),
    };
    Ok(resp)
}

#[tokio::main]
async fn main() -> Result<(), Error> {
    tracing_subscriber::fmt()
        .with_max_level(tracing::Level::INFO)
        .with_target(false)
        .without_time()
        .init();

    run(service_fn(function_handler)).await
}

```

**Comment by calavera** [comment] 2024-11-01 18:57
how did you create this project? Is it something SAM generated for you? That's not a valid HTTP handler, so I'm wondering if this is autogenerated, and should be corrected somewhere else to prevent more people from bumping into the same problem

**Comment by paulsmithkc** [comment] 2024-11-01 19:45
Project was created by the sam cli
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html

**Comment by calavera** [comment] 2024-11-01 21:33
The handler is different than what the HTTP handlers need to be. Here's a basic HTTP example:

https://github.com/awslabs/aws-lambda-rust-runtime/blob/main/examples/http-basic-lambda/src/main.rs#L1-L7

You can run your code with `cargo lambda watch`, but you cannot call it via HTTP because this reason. You can call it however with the invoke subcommand: https://www.cargo-lambda.info/commands/invoke.html#ascii-data

**Comment by calavera** [comment] 2024-11-04 18:13
I'm going to close this issue as the problem is with the function that doesn't follow the expected http handler. The Rust Runtime README has more information about handling HTTP traffic that I recommend you to check out: https://github.com/awslabs/aws-lambda-rust-runtime/tree/main/lambda-http#readme

**Closed by calavera** 2024-11-04 18:13 UTC
