### ISSUE TITLE
--include flag doesn't recognize relative path '..'

### ISSUE THREAD

**Issue by ik1ne** [cargo-lambda/cargo-lambda#685] opened 2024-08-28 02:02 UTC
When I build `cargo lambda build --output-format zip --include ../config/`, the created bootstrap.zip doesn't include the config file.
If I provide the config path as an absolute path(`/.../config`), the config folder is included in the final zip archive.

**Comment by calavera** [comment] 2024-08-28 15:11
Thanks for opening this issue. Feel free to create a Pull Request with a fix for this behavior.

**Comment by calavera** [comment] 2024-09-14 18:55
I think the problem is that when you include a relative path, it will be unzipped exactly in the same location, relative where the command `unizp` runs. This is a general problem because the files included in the deployment zip will be called `../config/FILE`.

I added an improvement in #696 that allows you to change the name of the destination directory that's created inside the zip file. In your case, using the new expression `--include config:../config` will create the file structure inside the zip file as `config/FILE` instead of `../config/FILE`.

**Closed** 2024-09-14 21:24 UTC
Labels: bug, commands/build
